### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by MoAlSeifi** [svonjoi/obsidian-heading-level-indent#34]
Can you make the Indentation Bi-Directional, since when typing in Right-To-Left direction, the indents will go further than number line.
(it's better to automatically decide direction of indentation, for multi-language documents and headers)
thanks

**Comment by Luiyems** [comment]
I believe this issue is resolved in the following PR: #40

The fix corrects RTL indentation in preview/edit mode and ensures indentation is preserved when exporting notes to PDF.

Please let me know if any adjustments are needed.

**Comment by IslamGoher** [comment]
@MoAlSeifi @svonjoi @Luiyems 
I was able to solve the RTL problem in 2 steps:
1. Editing mode
    * I used the code from the PR [#40](https://github.com/svonjoi/obsidian-heading-level-indent/pull/40)
    * I cloned the repo, installed the dependencies, and ran `npm run build`
    * Then I replace the file `main.js` from `/.obsidian/plugins/heading-level-indent` with the generated `main.js` file after building.
2. Preview Mode
    * I added the following CSS snippet to Obsidian
    * Note: You can edit the indent values based on the plugin configs
    ```CSS
    :root {
		--indent-h2: 20px;
		--indent-h3: 40px;
		--indent-h4: 60px;
		--indent-h5: 80px;
		--indent-h6: 100px;
	}

	.markdown-reading-view [class*="data_h2"],
	.markdown-reading-view [class*="heading_h2"] {
		margin-left: unset !important;
		margin-inline-start: var(--indent-h2) !important;
	}

	.markdown-reading-view [class*="data_h3"],
	.markdown-reading-view [class*="heading_h3"] {
		margin-left: unset !important;
		margin-inline-start: var(--indent-h3) !important;
	}

	.markdown-reading-view [class*="data_h4"],
	.markdown-reading-view [class*="heading_h4"] {
		margin-left: unset !important;
		margin-inline-start: var(--indent-h4) !important;
	}

	.markdown-reading-view [class*="data_h5"],
	.markdown-reading-view [class*="heading_h5"] {
		margin-left: unset !important;
		margin-inline-start: var(--indent-h5) !important;
	}

	.markdown-reading-view [class*="data_h6"],
	.markdown-reading-view [class*="heading_h6"] {
		margin-left: unset !important;
		margin-inline-start: var(--indent-h6) !important;
	}

    ```

**Comment by MoAlSeifi** [comment]
I've updated the plug-in to the latest version (2.1.1), though it still doesn't have the correct behavior.

<img width="84" height="219" alt="Image" src="https://github.com/user-attachments/assets/e433149b-81e7-46b8-86e6-a2847f953aaf" />

as for solution of @IslamGoher , I don't have a clue how to add these CSS snippets to obsidian, so the issue persists.

**Comment by StormBlackthorn** [comment]
Maybe a RTL setting could be added that applies the CSS snippet on the plugin side?
